name: 'Production Deployment'

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Create .ssh Directory and known_hosts file
        run: mkdir -p ~/.ssh && touch ~/.ssh/known_hosts

      - name: Add SSH known_hosts
        run: ssh-keyscan -H agency.cyber32.com >> ~/.ssh/known_hosts

      - name: Store private key in a temporary file
        run: echo "${{secrets.KEY}}" >> /tmp/private_key && chmod 600 /tmp/private_key

      - name: Deploy to Server
        run: |
          echo "Deploying to Server"
          ssh -vvv -o "IdentitiesOnly=yes" -i /tmp/private_key -p 22 cybejryn@agency.cyber32.com \
            "cd agency.cyber32.com && git pull origin main && ./php artisan migrate --force && ./php artisan optimize"

      - name: Cleanup
        run: rm /tmp/private_key